### ISSUE TITLE
Error while evaluating the constraint Jacobian using NLPtoMPB

### ISSUE THREAD

**Issue by scotthanton** [JuliaSmoothOptimizers/NLPModels.jl#81] opened 2017-02-27 23:06 UTC
I am using AmplNLReader to read a non-linear problem from an NL file.

`m = AmplModel(filename)`

I am trying to convert it to an Ipopt model using the following code

`ipoptmodel = NLPtoMPB(m, IpoptSolver());`

and I am receiving the following error 

> Error while evaluating constraints Jacobian

Which occurs in ampl_mode.jl on line 313. 

Am I doing something incorrectly here?

**Comment by vepiteski** [comment] 2017-02-28 02:39
Under Ubuntu 14.04, I intermittently get this error message. My student uses Ubuntu 16.04 and never gets it; Dominique Orban never gets it on MacOS. My  opinion is that it is an OS dependant bug.

**Comment by scotthanton** [comment] 2017-02-28 03:54
I'm using Fedora 23. It seems to happen intermittently for me too, as it has randomly begun working.

**Comment by dpo** [comment] 2017-03-01 15:45
I'm frankly not sure how to resolve this. The bug appears to be related to the interaction between the ASL and the OS. Either way, I don't think the bug is in NLPModels so I'll go ahead and close this. If you think the issue is in AmplNLReader, feel free to open an issue over there.

**Closed by dpo** 2017-03-01 15:45 UTC
